# © 2026 Daniel Partel – SIRIUS Assistant. Storyboard publicitaire PROMO# (15 plans).
PROMO_SHOTS = [
    {
        "id": 1, "title": "LA PLATEFORME", "timecode": "0:00 – 0:07",
        "scene": "Noir total. Le réacteur doré de SIRIUS s'éveille : anneaux concentriques or, pulsations cyan, symboles grecs en orbite. Montée en puissance immédiate.",
        "ambiance": "Impact sonore sourd, nappe qui monte. Affirmation, rupture.",
        "visuels": "Zoom avant sur le noyau, particules d'or, éclats cyan, clair-obscur publicitaire.",
        "message": "Rupture de positionnement : SIRIUS n'est pas un gadget, c'est une plateforme.",
        "voix": "SIRIUS n'est pas un assistant. C'est une plateforme d'intelligence opérationnelle.",
        "image": "/api/promo/img/shot1.jpg",
    },
    {
        "id": 2, "title": "LA TRANSFORMATION", "timecode": "0:07 – 0:14",
        "scene": "Le temple holographique doré se construit en fils de lumière : colonnes, amphore, flux cyan. L'utilisateur entre dans un autre monde.",
        "ambiance": "Majestueux, promesse d'élévation.",
        "visuels": "Wireframe or en construction, reflets cyan, travelling ascendant.",
        "message": "SIRIUS élève chaque utilisateur au rang de sur-performant.",
        "voix": "Elle transforme n'importe quel utilisateur — particulier ou entreprise — en acteur sur-performant.",
        "image": "/api/promo/img/shot2.jpg",
    },
    {
        "id": 3, "title": "LE CERVEAU", "timecode": "0:14 – 0:19",
        "scene": "Un cerveau de lumière dorée tourne entre les colonnes, ceint d'anneaux cyan de données. Graphiques et rouages traités à grande vitesse.",
        "ambiance": "Quatre impacts rythmés, un par verbe.",
        "visuels": "Cerveau doré, anneaux data cyan, traînées de lumière ultra-rapides.",
        "message": "Les 4 verbes de SIRIUS : analyser, automatiser, anticiper, exécuter.",
        "voix": "SIRIUS analyse. Automatise. Anticipe. Et exécute.",
        "image": "/api/promo/img/shot11.jpg",
    },
    {
        "id": 4, "title": "L'EFFICACITÉ", "timecode": "0:19 – 0:26",
        "scene": "L'œil de l'Oracle doré au-dessus de la vasque : courbes de coûts qui chutent, graphiques de décision qui s'accélèrent.",
        "ambiance": "Précision chirurgicale, confiance.",
        "visuels": "Œil hologramme or/cyan, charts lumineux, ambiance divinatoire.",
        "message": "Trois bénéfices concrets : coûts, vitesse, fluidité.",
        "voix": "Elle réduit les coûts, accélère les décisions, et élimine les frictions.",
        "image": "/api/promo/img/shot7.jpg",
    },
    {
        "id": 5, "title": "LE CHAOS ACTUEL", "timecode": "0:26 – 0:39",
        "scene": "Rupture visuelle : des dizaines de fenêtres d'applications éparpillées, câbles emmêlés, une silhouette débordée qui jongle entre les écrans. Lumière froide, grise.",
        "ambiance": "Stress, friction, gâchis. Le seul plan volontairement terne du film.",
        "visuels": "Fenêtres dispersées, gris/bleu froid, silhouette débordée — contraste maximal avec l'or de SIRIUS.",
        "message": "Le problème : outils dispersés, process inefficaces, tâches répétitives.",
        "voix": "Aujourd'hui, les entreprises dépensent des fortunes en outils dispersés, en process inefficaces, en tâches répétitives. Et les particuliers jonglent entre dix applications pour ce qu'un seul système devrait gérer.",
        "image": "/api/promo/img/shot12.jpg",
    },
    {
        "id": 6, "title": "LA CONVERGENCE", "timecode": "0:39 – 0:47",
        "scene": "Toutes les fenêtres éparses sont aspirées et fusionnent en UNE seule interface dorée frappée du Sigma Σ. L'ordre naît du chaos.",
        "ambiance": "Résolution triomphante, retour de l'or.",
        "visuels": "Faisceaux d'or convergents, panneau unique doré, emblème Σ central rayonnant.",
        "message": "La solution : une interface, un cerveau, un flux.",
        "voix": "SIRIUS remplace tout ça. Une seule interface. Un seul cerveau. Un seul flux d'action.",
        "image": "/api/promo/img/shot13.jpg",
    },
    {
        "id": 7, "title": "LA TECHNOLOGIE", "timecode": "0:47 – 0:54",
        "scene": "La constellation des neuf emblèmes dorés du Panthéon s'allume module après module, reliée par des fils cyan.",
        "ambiance": "Démonstration de force, un battement par emblème.",
        "visuels": "Constellation d'emblèmes mythologiques, rayonnement central, connexions animées.",
        "message": "Bénéfices technologiques 1 et 2 : temps gagné, automatisation sans configuration.",
        "voix": "Réduction immédiate du temps opérationnel. Automatisation intelligente, sans configuration.",
        "image": "/api/promo/img/shot5.jpg",
    },
    {
        "id": 8, "title": "L'INTELLIGENCE", "timecode": "0:54 – 1:03",
        "scene": "L'onde vocale cyan vibre et explose en particules d'or à chaque bénéfice énoncé. ΣIRIUS s'illumine au-dessus.",
        "ambiance": "Rythme en triptyque, précision.",
        "visuels": "Waveform cyan réactive, lettres grecques dorées, bokeh d'or.",
        "message": "Bénéfices 3, 4, 5 : décision assistée, intégration fluide, adoption instantanée.",
        "voix": "Prise de décision assistée par IA. Intégration fluide dans n'importe quel workflow. Adoption instantanée, par n'importe quel utilisateur.",
        "image": "/api/promo/img/shot4.jpg",
    },
    {
        "id": 9, "title": "LE MARCHÉ", "timecode": "1:03 – 1:11",
        "scene": "Le globe holographique doré porté par la main de marbre : les continents s'allument secteur après secteur.",
        "ambiance": "Ampleur, vertige des chiffres.",
        "visuels": "Globe 3D or, routes cyan, secteurs qui s'illuminent un à un.",
        "message": "Taille du marché : productivité, IA personnelle, automatisation, optimisation métier.",
        "voix": "Le marché est gigantesque : productivité, IA personnelle, automatisation, assistants intelligents, optimisation métier.",
        "image": "/api/promo/img/shot6.jpg",
    },
    {
        "id": 10, "title": "L'APPROCHE UNIQUE", "timecode": "1:11 – 1:20",
        "scene": "Le Gardien holographique or et cyan s'avance sur son halo, regard caméra. Silence avant la punchline.",
        "ambiance": "Solennel, suspension… puis frappe.",
        "visuels": "Gardien translucide, halo pulsant, colonnes floues.",
        "message": "La signature : un assistant qui agit, pas qui répond.",
        "voix": "SIRIUS se positionne au centre de ces secteurs, avec une approche unique : un assistant qui ne répond pas… un assistant qui agit.",
        "image": "/api/promo/img/shot3.jpg",
    },
    {
        "id": 11, "title": "L'AVANTAGE", "timecode": "1:20 – 1:29",
        "scene": "La forge d'Héphaïstos : le marteau doré frappe l'enclume à chaque phrase. Gerbes d'étincelles or et cyan.",
        "ambiance": "Percussion : un impact de marteau par argument.",
        "visuels": "Marteau incandescent, étincelles volumétriques, anneaux de forge.",
        "message": "Pitch de vente : pas un outil — un avantage, un levier, un accélérateur.",
        "voix": "Nous ne vendons pas un outil. Nous vendons un avantage. Un levier de performance. Un accélérateur de croissance.",
        "image": "/api/promo/img/shot8.jpg",
    },
    {
        "id": 12, "title": "L'INDISPENSABLE", "timecode": "1:29 – 1:39",
        "scene": "Le faisceau cyan analyse un document qui se dissout en or ; l'œil de la Vision balaie entreprises et particuliers.",
        "ambiance": "Proximité, chacun se reconnaît.",
        "visuels": "Faisceau vertical cyan, particules d'or, œil d'analyse, viewer 3D.",
        "message": "Cibles : entreprises (coûts) et particuliers (temps).",
        "voix": "SIRIUS est conçu pour devenir indispensable. Pour les entreprises qui veulent réduire leurs coûts. Pour les particuliers qui veulent gagner du temps.",
        "image": "/api/promo/img/shot9.jpg",
    },
    {
        "id": 13, "title": "LA VITESSE", "timecode": "1:39 – 1:45",
        "scene": "Une comète d'or file entre les colonnes, un coureur de lumière dorée sprinte devant elle. Diagonale de vitesse pure.",
        "ambiance": "Accélération, souffle.",
        "visuels": "Comète dorée, traînées or/cyan, silhouette de coureur en lumière.",
        "message": "Promesse universelle : plus vite, plus loin, moins d'effort.",
        "voix": "Pour tous ceux qui veulent aller plus vite, plus loin, avec moins d'effort.",
        "image": "/api/promo/img/shot14.jpg",
    },
    {
        "id": 14, "title": "L'INVESTISSEMENT", "timecode": "1:45 – 1:56",
        "scene": "Un escalier-courbe de croissance en or monte vers les étoiles, couronné de lauriers grecs. Flèches et graphiques ascendants.",
        "ambiance": "Confiance, envolée orchestrale.",
        "visuels": "Courbe dorée en escalier céleste, lauriers, ciel cyan étoilé.",
        "message": "Appel aux investisseurs : la prochaine génération d'assistants.",
        "voix": "Investir dans SIRIUS, c'est investir dans la prochaine génération d'assistants intelligents : un système qui ne se contente pas d'aider, mais qui exécute, optimise, et transforme.",
        "image": "/api/promo/img/shot15.jpg",
    },
    {
        "id": 15, "title": "SIRIUS", "timecode": "1:56 – 2:03",
        "scene": "Le titre ΣIRIUS en or massif explose en particules d'or et de cyan sous l'étoile la plus brillante. Fondu vers le carton final.",
        "ambiance": "Apothéose, puis note finale cristalline.",
        "visuels": "Typographie grecque monumentale, explosion de particules, lens flare, étoile Sirius.",
        "message": "Signature finale : la puissance opérationnelle, accessible à tous.",
        "voix": "SIRIUS. La puissance opérationnelle, accessible à tous.",
        "image": "/api/promo/img/shot10.jpg",
    },
]
