export function createModuleRegistry({ icons, actions, state, user }) {
  const { ThemisLogo, PantheonLogo, MythosLogo } = icons;
  const {
    reload,
    toggleDisplay,
    showMediaModules,
    openFiles,
    openInfoHub,
    openConnections,
    captureInterface,
    captureRegion,
    openCaptureFolder,
    openArchitect,
    openPlans,
    openPhoto3d,
    openPantheon,
    openCortex,
    openNexus,
    openOracle,
    openNummarius,
    openEuropeana,
    openHaccp,
    openPrime,
    openDev,
    openAnalytics,
    openMemory,
    openMemoryManager,
    openArgus,
    openJournal,
    openKeys,
    openCalendar,
    openFaceId,
    openReveil,
    openKeraunos,
    openEspace,
    openAbout,
    openLocus,
    openAtlas,
    openHeracles,
    openHephaistos,
    openMythos,
    openTrailer,
    openPromo,
    openThemis,
    openAgora,
    openSolon,
    openPromethee,
    openCalliope,
    openPythagore,
    openNews,
    openPackager,
    openInstall,
    openScripts,
    toggleVision,
    openProductivity,
    openMedia,
    openSpotify,
    openAdmin,
    openEnterprise,
    openWorkModule,
  } = actions;

  return [
    { id: "reload", group: "SYSTÈME", label: "Recharger ΣIRIUS", Icon: icons.RotateCcw, run: reload },
    { id: "display", group: "MÉDIAS", label: "ΣIRIUS DISPLAY", Icon: icons.Monitor, active: state.displayOpen, run: toggleDisplay },
    { id: "media-modules", group: "MÉDIAS", label: "Modules multimédia", Icon: icons.Clapperboard, active: state.displayOpen && state.displayType === "media", run: showMediaModules },
    { id: "files", group: "MÉDIAS", label: "Médiathèque", Icon: icons.FolderOpen, run: openFiles },
    { id: "info-hub", group: "OUTILS", label: "Centre d'information SIRIUS", Icon: icons.BadgeInfo, run: openInfoHub },
    { id: "connections", group: "OUTILS", label: "Comptes & connexions", Icon: icons.Link2, run: openConnections },
    { id: "capture-interface", group: "OUTILS", label: "Capture de l'interface", Icon: icons.Camera, run: captureInterface },
    { id: "capture-region", group: "OUTILS", label: "Capture d'une zone (souris)", Icon: icons.Camera, run: captureRegion },
    { id: "open-capture-folder", group: "OUTILS", label: "Ouvrir le dossier des captures", Icon: icons.FolderOpen, run: openCaptureFolder },
    { id: "architect", group: "OUTILS", label: "Architecte visuel", Icon: icons.Workflow, run: openArchitect },
    { id: "plans", group: "OUTILS", label: "Plans 2D (PLANS#)", Icon: icons.Ruler, run: openPlans },
    { id: "photo3d", group: "OUTILS", label: "Photos → Objet 3D (PHOTO3D#)", Icon: icons.Boxes, run: openPhoto3d },
    { id: "pantheon", group: "PANTHÉON", label: "PANTHEON SYSTEM", Icon: PantheonLogo, run: openPantheon },
    { id: "cortex", group: "PANTHÉON", label: "ZEUS CORTEX# — intelligence centrale", Icon: icons.Zap, run: openCortex },
    { id: "nexus", group: "PANTHÉON", label: "NEXUS CÉLESTE", Icon: icons.Orbit, run: openNexus },
    { id: "oracle", group: "PANTHÉON", label: "ORACLE DIVIN", Icon: icons.Eye, run: openOracle },
    { id: "nummarius", group: "PANTHÉON", label: "PORTUS NUMMARIUS# — bourse & marchés", Icon: icons.Landmark, run: openNummarius },
    { id: "europeana", group: "MÉDIAS", label: "Archives Europeana", Icon: icons.Library, run: openEuropeana },
    { id: "haccp", group: "OUTILS", label: "HACCP — sécurité alimentaire", Icon: icons.ShieldCheck, run: openHaccp },
    { id: "prime", group: "OUTILS", label: "ΣIRIUS PRIME — mémoire", Icon: icons.Sparkles, run: openPrime },
    { id: "dev", group: "OUTILS", label: "Compagnon Dev", Icon: icons.Code2, run: openDev },
    { id: "analytics", group: "OUTILS", label: "Tableau analytique", Icon: icons.BarChart3, run: openAnalytics },
    { id: "memory", group: "OUTILS", label: "Ce que Sirius sait sur moi", Icon: icons.Brain, run: openMemory },
    { id: "memorymgr", group: "OUTILS", label: "Gestion de la mémoire", Icon: icons.Database, run: openMemoryManager },
    { id: "argus", group: "PANTHÉON", label: "ARGUS — surveillance système", Icon: icons.Radar, run: openArgus },
    { id: "journal", group: "OUTILS", label: "Journal des tâches", Icon: icons.History, run: openJournal },
    { id: "keys", group: "SYSTÈME", label: "Statut des clés API", Icon: icons.KeyRound, run: openKeys },
    { id: "gcal", group: "OUTILS", label: "AGENDA — Google Calendar", Icon: icons.Calendar, run: openCalendar },
    { id: "faceid", group: "SYSTÈME", label: "FACE ID — reconnaissance faciale locale", Icon: icons.Fingerprint, run: openFaceId },
    { id: "reveil", group: "SYSTÈME", label: "RÉVEIL MATINAL — briefing & mails à l'heure choisie", Icon: icons.AlarmClock, run: openReveil },
    { id: "keraunos", group: "PANTHÉON", label: "KERAUNOS# — domotique", Icon: icons.HomeIcon, run: openKeraunos },
    { id: "espace", group: "MÉDIAS", label: "ESPACE — système solaire 3D", Icon: icons.Globe2, run: openEspace },
    { id: "about", group: "SYSTÈME", label: "À propos / Informations légales", Icon: icons.BadgeInfo, run: openAbout },
    { id: "locus", group: "PANTHÉON", label: "LOCUS# — géolocalisation", Icon: icons.MapPin, run: openLocus },
    { id: "atlas", group: "PANTHÉON", label: "ATLAS# — carte & navigation", Icon: icons.Globe2, run: openAtlas },
    { id: "heracles", group: "PANTHÉON", label: "HERACLES# — investigation OSINT", Icon: icons.Fingerprint, run: openHeracles },
    { id: "hephaistos", group: "PANTHÉON", label: "HÉPHAÏSTOS# — auto-maintenance & diagnostic", Icon: icons.Hammer, mobile: false, run: openHephaistos },
    { id: "mythos", group: "PANTHÉON", label: "Galerie MYTHOS", Icon: MythosLogo, run: openMythos },
    { id: "trailer", group: "MÉDIAS", label: "TRAILER# — clichés cinématiques", Icon: icons.Clapperboard, run: openTrailer },
    { id: "promo", group: "MÉDIAS", label: "PROMO# — storyboard vidéo réseaux sociaux", Icon: icons.Radio, run: openPromo },
    { id: "themis", group: "PANTHÉON", label: "THÉMIS# — gestion d'entreprise (devis, factures, stocks)", Icon: ThemisLogo, run: openThemis },
    { id: "agora", group: "PANTHÉON", label: "HERMÈS AGORA# — pipeline de vente", Icon: icons.TrendingUp, run: openAgora },
    { id: "solon", group: "PANTHÉON", label: "SOLON# — conseil juridique", Icon: icons.Scale, run: openSolon },
    { id: "promethee", group: "PANTHÉON", label: "PROMÉTHÉE# — gestion de projet", Icon: icons.Flame, run: openPromethee },
    { id: "workflows", group: "PANTHÉON", label: "ARIANE# — orchestration des modules", Icon: icons.Workflow, run: () => openWorkModule("workflows") },
    { id: "pricing", group: "PANTHÉON", label: "PLUTOS# — prix et fournisseurs", Icon: icons.Landmark, run: () => openWorkModule("pricing") },
    { id: "dossiers", group: "PANTHÉON", label: "MNÉMOSYNE# — dossiers et archives", Icon: icons.FolderOpen, run: () => openWorkModule("dossiers") },
    { id: "audit", group: "PANTHÉON", label: "NÉMÉSIS# — audit et traçabilité", Icon: icons.History, run: () => openWorkModule("audit") },
    { id: "documents", group: "PANTHÉON", label: "THOT# — lecture et classement", Icon: icons.FileCode, run: () => openWorkModule("documents") },
    { id: "planning", group: "PANTHÉON", label: "CHRONOS# — planning et échéances", Icon: icons.Calendar, run: () => openWorkModule("planning") },
    { id: "calliope", group: "PANTHÉON", label: "CALLIOPE# — bibliothèque audio", Icon: icons.BookOpen, run: openCalliope },
    { id: "pythagore", group: "PANTHÉON", label: "PYTHAGORE# — mathématiques & géométrie", Icon: icons.Sigma, run: openPythagore },
    { id: "news", group: "MÉDIAS", label: "ACTUALITÉS — flux en direct", Icon: icons.Newspaper, run: openNews },
    { id: "packager", group: "OUTILS", label: "PACKAGER# — livrable multi-plateforme", Icon: icons.Package, mobile: false, run: openPackager },
    { id: "install", group: "SYSTÈME", label: "Assistant d'installation", Icon: icons.Wrench, mobile: false, run: openInstall },
    { id: "scripts", group: "OUTILS", label: "Bibliothèque de scripts", Icon: icons.FileCode, mobile: false, run: openScripts },
    { id: "vision", group: "MÉDIAS", label: "Vision caméra", Icon: icons.Camera, active: state.showVision, run: toggleVision },
    { id: "productivity", group: "OUTILS", label: "PRODUCTIVITE & TRAVAIL — documents, code, notes, taches", Icon: icons.Workflow, active: state.showProductivity, run: openProductivity },
    { id: "media", group: "MÉDIAS", label: "MEDIA PROXY — lecteurs et controles", Icon: icons.Radio, active: state.showMediaHud, run: openMedia },
    { id: "spotify", group: "MÉDIAS", label: state.spotify ? "Spotify — lecteur intégré" : "Spotify — lecteur (connexion requise)", Icon: icons.Music, active: state.spotify, run: openSpotify },
    ...(user?.role === "admin" ? [{ id: "admin", group: "SYSTÈME", label: "ADMINISTRATION — comptes & activité", Icon: icons.ShieldCheck, run: openAdmin }] : []),
    ...(user ? [{ id: "enterprise", group: "SYSTÈME", label: "SIRIUS ENTREPRISE — équipe, audit & sauvegardes", Icon: icons.Building2, run: openEnterprise }] : []),
  ];
}
