export const ODYSSEIA_HUD_QUOTES = [
  ["Connais-toi toi-même.", "Socrate"],
  ["Je ne sais qu'une chose, c'est que je ne sais rien.", "Socrate"],
  ["Le commencement est la moitié de tout.", "Pythagore"],
  ["On ne se baigne jamais deux fois dans le même fleuve.", "Héraclite"],
  ["L'excellence n'est pas un acte, mais une habitude.", "Aristote"],
  ["Le doute est le commencement de la sagesse.", "Aristote"],
  ["La patience est amère, mais son fruit est doux.", "Aristote"],
  ["Nul n'est méchant volontairement.", "Platon"],
  ["La musique donne une âme à nos cœurs et des ailes à la pensée.", "Platon"],
  ["Il n'y a qu'un chemin vers le bonheur : cesser de s'inquiéter des choses qui ne dépendent pas de notre volonté.", "Épictète"],
  ["Ce qui trouble les hommes, ce ne sont pas les choses, mais les jugements qu'ils portent sur elles.", "Épictète"],
  ["Hâte-toi de bien vivre et songe que chaque jour est à lui seul une vie.", "Sénèque"],
  ["La fortune sourit aux audacieux.", "Virgile"],
  ["Tout ce que nous entendons est une opinion, non un fait. Tout ce que nous voyons est une perspective, non la vérité.", "Marc Aurèle"],
  ["Le bonheur de ta vie dépend de la qualité de tes pensées.", "Marc Aurèle"],
].map(([text, voice]) => ({ text, voice, origin: "hud", attributionUnverified: true }));

export const ODYSSEIA_HUD_INSPIRATIONS = [
  ["Les douze travaux commencent tous par le premier geste.", "HERACLES"],
  ["La rigueur d'aujourd'hui est le bouclier de demain.", "HERACLES"],
  ["Nul exploit sans discipline : la propreté est ma treizième épreuve.", "HERACLES"],
  ["La force ne sert à rien sans la constance qui la guide.", "HERACLES"],
  ["Dans ma forge, chaque panne est un métal qui attend d'être redressé.", "HÉPHAÏSTOS"],
  ["Ce qui est cassé peut renaître plus fort, si la main qui répare est patiente.", "HÉPHAÏSTOS"],
  ["Le feu ne détruit que ce qu'on refuse de façonner.", "HÉPHAÏSTOS"],
  ["Un outil bien entretenu vaut mieux que cent promesses.", "HÉPHAÏSTOS"],
  ["La justice sans rigueur n'est qu'une opinion ; la rigueur sans justice, une tyrannie.", "THÉMIS"],
  ["Un compte exact est une parole tenue.", "THÉMIS"],
  ["L'équilibre de la balance se gagne chiffre après chiffre.", "THÉMIS"],
  ["Ce qui est écrit et signé protège celui qui a donné sa parole.", "THÉMIS"],
  ["Vendre, c'est d'abord écouter ce que l'autre n'ose pas dire.", "HERMÈS"],
  ["Une objection n'est pas un mur : c'est une porte qui demande la bonne clé.", "HERMÈS"],
  ["Le meilleur messager livre la vérité avec le sourire du marchand.", "HERMÈS"],
  ["L'affaire conclue trop vite se dénoue de même ; prends le temps de la confiance.", "HERMÈS"],
  ["Cent yeux ne suffisent pas si aucun ne sait ce qu'il cherche.", "ARGUS"],
  ["La vigilance est un art silencieux : on ne la remarque que lorsqu'elle manque.", "ARGUS"],
  ["Ce que tu surveilles avec constance ne te trahira jamais par surprise.", "ARGUS"],
  ["La foudre ne frappe pas au hasard : elle choisit le point le plus haut.", "KERAUNOS"],
  ["La puissance sans maîtrise n'est qu'un orage perdu.", "KERAUNOS"],
  ["Un seul éclair suffit à révéler tout un paysage.", "KERAUNOS"],
  ["Régner, c'est décider quand tous hésitent encore.", "ZEUS"],
  ["Du sommet de l'Olympe, les grands problèmes redeviennent petits.", "ZEUS"],
  ["L'ordre du monde tient à ceux qui veillent quand les autres dorment.", "ZEUS"],
  ["Chaque lieu garde la mémoire de ceux qui l'ont traversé.", "LOCUS"],
  ["Savoir où l'on est, c'est déjà savoir qui l'on est.", "LOCUS"],
  ["Le chemin le plus court n'est pas toujours celui qui t'apprend le plus.", "LOCUS"],
].map(([text, voice]) => ({ text, voice, origin: "hud" }));

export const ODYSSEIA_QUOTES = [
  ...[
  ["La sagesse est l'arme que nul bouclier ne peut arrêter.", "Athéna"],
  ["Celui qui connaît son destin n'en est pas l'esclave.", "Apollon"],
  ["La vérité éclaire ceux qui osent la regarder.", "Athéna"],
  ["Le savoir est la plus haute des conquêtes.", "Thot"],
  ["Les dieux accordent des signes, jamais des certitudes.", "Hermès"],
  ["La connaissance survit lorsque les royaumes tombent.", "Thot"],
  ["Nul mortel n'échappe au fil tissé par les Moires.", "Mythologie grecque"],
  ["Le destin ouvre toujours la route que l'homme refuse de voir.", "Mythologie grecque"],
  ["Même les dieux respectent certaines lois du destin.", "Mythologie grecque"],
  ["Chaque étoile porte l'écho d'un avenir possible.", "Mythologie grecque"],
  ["Le chemin est écrit, mais le courage appartient au voyageur.", "Mythologie grecque"],
  ["La gloire appartient à ceux qui avancent malgré la peur.", "Arès"],
  ["Un héros naît lorsqu'il refuse d'abandonner.", "Mythologie grecque"],
  ["Les plus grandes victoires commencent par une seule décision.", "Mythologie grecque"],
  ["Le cœur brave vaut mieux qu'une armée hésitante.", "Mythologie grecque"],
  ["Les tempêtes révèlent la force des navigateurs.", "Mythologie grecque"],
  ["Le courage transforme l'impossible en légende.", "Mythologie grecque"],
  ["Tout voyage commence avant le premier pas.", "Ulysse"],
  ["Les mers inconnues forgent les âmes immortelles.", "Ulysse"],
  ["Le retour est parfois plus grand que le départ.", "Ulysse"],
  ["Celui qui cherche trouve davantage que ce qu'il poursuivait.", "Ulysse"],
  ["Les horizons s'éloignent pour inviter l'homme à avancer.", "Ulysse"],
  ["La destination importe moins que ce que le voyage révèle.", "Ulysse"],
  ["Le temps dévore les empires mais préserve les légendes.", "Chronos"],
  ["Ce qui est oublié cesse d'exister.", "Chronos"],
  ["Les siècles passent, les mythes demeurent.", "Chronos"],
  ["Chaque aurore est une victoire sur la nuit.", "Chronos"],
  ["L'éternité appartient aux récits transmis.", "Chronos"],
  ["Gouverner exige davantage de justice que de puissance.", "Zeus"],
  ["Le tonnerre avertit avant de frapper.", "Zeus"],
  ["Le pouvoir sans sagesse appelle sa propre chute.", "Zeus"],
  ["Le ciel appartient à ceux qui savent l'observer.", "Zeus"],
  ["La mer récompense les audacieux et éprouve les orgueilleux.", "Poséidon"],
  ["Les vagues ignorent les certitudes des hommes.", "Poséidon"],
  ["Tout port sûr fut atteint après une tempête.", "Poséidon"],
  ["L'océan enseigne la patience aux plus impatients.", "Poséidon"],
  ["Toute vie tire sa valeur de sa fin.", "Hadès"],
  ["Les ombres gardent les secrets que la lumière ignore.", "Hadès"],
  ["Aucun roi n'emporte son trône dans l'au-delà.", "Hadès"],
  ["Les morts reposent, les légendes voyagent encore.", "Hadès"],
  ["Le véritable guerrier combat d'abord ses propres peurs.", "Odin"],
  ["La connaissance exige toujours un sacrifice.", "Odin"],
  ["Le destin favorise les courageux.", "Odin"],
  ["Même les dieux affrontent leur crépuscule.", "Odin"],
  ["L'honneur survit lorsque la chair disparaît.", "Odin"],
  ["Le cœur est plus lourd que l'or lorsqu'il porte le mensonge.", "Maât"],
  ["Celui qui respecte l'équilibre défie le chaos.", "Maât"],
  ["Le soleil renaît parce qu'il refuse de mourir.", "Rê"],
  ["L'ordre est la victoire quotidienne sur les ténèbres.", "Rê"],
  ["Les légendes ne racontent pas le passé, elles éclairent l'avenir.", "ODYSSEIA"],
  ["Chaque mythe est une vérité cachée derrière un symbole.", "ODYSSEIA"],
  ["Les dieux parlent encore à ceux qui savent écouter.", "ODYSSEIA"],
  ["L'histoire s'efface, le mythe demeure.", "ODYSSEIA"],
  ["Là où finit la mémoire commence la légende.", "ODYSSEIA"],
  ["Les étoiles sont les bibliothèques des anciens dieux.", "ODYSSEIA"],
  ["Le savoir est l'héritage le plus sacré des immortels.", "ODYSSEIA"],
  ["Les civilisations passent, les mythes traversent les âges.", "ODYSSEIA"],
  ["Cherche la sagesse plutôt que la puissance, et la puissance te suivra.", "ODYSSEIA"],
  ["Les récits anciens sont la mémoire éternelle de l'humanité.", "ODYSSEIA"],
  ].map(([text, voice]) => ({ text, voice })),
  ...ODYSSEIA_HUD_QUOTES,
  ...ODYSSEIA_HUD_INSPIRATIONS,
];

export const ODYSSEIA_HISTORY = [
  {
    id: "name",
    title: "Pourquoi ODYSSEIA ?",
    text: "Le nom évoque l'Odyssée, le grand récit grec du retour d'Ulysse après la guerre de Troie. Le mot est devenu synonyme de long voyage, d'épreuves et de découvertes. ODYSSEIA présente les mythes comme des récits transmis par des sociétés, pas comme des chroniques factuelles.",
  },
  {
    id: "sirius",
    title: "Pourquoi ΣIRIUS ?",
    text: "Sirius est l'étoile la plus brillante du ciel nocturne vue depuis la Terre et se trouve dans la constellation du Grand Chien. Son nom grec ancien, Seírios, est traditionnellement associé à l'idée d'un éclat ardent. L'Antiquité a ainsi mêlé observation du ciel, calendrier, poésie et imaginaire religieux.",
  },
  {
    id: "egypt",
    title: "Sopdet et l'Égypte ancienne",
    text: "Dans la tradition égyptienne, Sopdet (appelée Sothis en grec) est associée à l'étoile Sirius. Son lever héliaque — sa première réapparition à l'aube après une période invisible — fut observé en relation avec le calendrier et le cycle du Nil. Cette relation dépendait du lieu et de l'époque : elle ne doit pas être comprise comme une date universelle ni comme une preuve que l'étoile causait la crue.",
  },
  {
    id: "greece",
    title: "Sirius dans la poésie grecque",
    text: "Dans l'Iliade (chant XXII), Homère compare l'éclat de l'armure d'Achille à Sirius, l'astre du Chien d'Orion, puis associe son apparition à une image inquiétante de chaleur et de fièvre. C'est une comparaison poétique antique, non une explication scientifique. Hésiode évoque également Sirius dans Les Travaux et les Jours, au fil des repères saisonniers.",
  },
  {
    id: "traditions",
    title: "Des mythologies, pas une seule",
    text: "Les figures grecques, égyptiennes et nordiques de cette collection viennent de cultures et de périodes différentes. ODYSSEIA les rapproche pour faciliter la découverte, sans prétendre qu'elles appartiennent à une même religion ou qu'elles racontent une histoire unique.",
  },
];

export const ODYSSEIA_SOURCES = [
  {
    label: "Homère, Iliade, XXII, 26–31 — texte grec et traduction anglaise",
    href: "https://www.perseus.tufts.edu/hopper/text?doc=Hom.+Il.+22.26",
  },
  {
    label: "Hésiode, Les Travaux et les Jours — texte et traduction",
    href: "https://www.perseus.tufts.edu/hopper/text?doc=Hes.+WD+609",
  },
  {
    label: "Richard A. Parker, The Calendars of Ancient Egypt, SAOC 26, 1950",
    href: "https://books.google.com/books?q=The+Calendars+of+Ancient+Egypt+Parker",
  },
  {
    label: "SIMBAD, base astronomique du Centre de données astronomiques de Strasbourg — Sirius",
    href: "https://simbad.cds.unistra.fr/simbad/sim-id?Ident=Sirius",
  },
];
